import { createSlice } from '@reduxjs/toolkit';

// import table image
import shose from '../../data/Icons/image shose.png';
import carImage from '../../data/Icons/image car.png';
import editIcon from '../../data/Icons/editt 2.svg';

const categoriesDataTable = [
	{
		productNumber: '01',
		SKU: 9586,
		productName: '  12 ايفون',
		productImg: shose,
		productCategory: 'اجهزة جوال',
		price: 4,
		total: 344,
		editIcon: editIcon,
		opened: false,
	},
	{
		productNumber: '02',
		SKU: 9586,
		productName: ' سماعة هدفون',
		productImg: carImage,
		productCategory: 'اكسسوارات',
		price: 41,
		total: 384,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '03',
		SKU: 996,
		productName: '  12 ايفون',
		productImg: shose,
		productCategory: 'اجهزة جوال',
		price: 2,
		total: 365,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '04',
		SKU: 186,
		productName: '  لابتوب Dell S2',

		productCategory: 'لابتوب',
		price: 51,
		total: 365,
		productImg: carImage,
		editIcon: editIcon,
		opened: false,
	},
	{
		productNumber: '05',
		SKU: 9586,
		productName: ' سماعة هدفون',
		productImg: shose,
		productCategory: 'لابتوتب',

		price: 24,
		total: 187,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '06',
		SKU: 9586,
		productName: '  بور بانك سامسونج',
		productCategory: 'بور بانك',
		productImg: shose,
		subNumber: 4,
		price: 344,
		total: 1709,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '07',
		SKU: 9586,
		productName: '  12 ايفون',
		productCategory: 'اجهزة جوال',
		productImg: shose,
		price: 204,
		total: 185,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '08',
		SKU: 9586,
		productName: ' سماعة هدفون',
		productImg: shose,
		productCategory: 'لابتوتب',
		price: 87,
		total: 456,

		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '09',
		SKU: 9586,
		productName: '  بور بانك سامسونج',
		productCategory: 'بور بانك',
		productImg: shose,
		price: 2354,
		total: 13287,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '10',
		SKU: 9586,
		productName: '  لابتوب Dell S2',
		productCategory: 'لابتوب',
		productImg: shose,
		price: 214,
		total: 787,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '11',
		SKU: 9586,
		productName: '  12 ايفون',
		productCategory: 'اجهزة جوال',
		productImg: shose,
		price: 240,
		total: 498,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '12',
		SKU: 9586,
		productName: '  بور بانك سامسونج',
		productCategory: 'بور بانك',
		productImg: shose,
		price: 24,
		total: 187,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '13',
		SKU: 9586,
		productName: ' سماعة هدفون',
		productCategory: 'اكسسوارات',
		productImg: shose,
		price: 14,
		total: 487,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '14',
		SKU: 9586,
		productName: '  لابتوب Dell S2',
		editIcon: editIcon,
		productCategory: 'لابتوب',
		price: 123,
		total: 654,
		productImg: shose,
		opened: true,
	},
	{
		productNumber: '15',
		idNumbSKUers: 9586,
		productName: '  بور بانك سامسونج',
		productCategory: 'بور بانك',
		productImg: shose,
		price: 487,
		total: 986,
		editIcon: editIcon,
		opened: true,
	},
	{
		productNumber: '16',
		SKU: 9586,
		productName: '  12 ايفون',
		productCategory: 'اجهزة جوال',
		productImg: shose,
		price: 4,
		total: 123,
		editIcon: editIcon,
		opened: true,
	},
];

// slices
const BigProductsTableDataSlice = createSlice({
	name: 'categoriesDataTable',
	initialState: categoriesDataTable,
	reducers: {},
});

export const {} = BigProductsTableDataSlice.actions;
export default BigProductsTableDataSlice.reducer;
