import { createSlice } from '@reduxjs/toolkit';

// import table image
import shose from '../../data/Icons/image shose.png';
import carImage from '../../data/Icons/image car.png';
import editIcon from '../../data/Icons/editt 2.svg';

const categoriesDataTable = [
	{
		id: '01',
		idNumbers: 9586,
		productName: 'جوالات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: false,
	},
	{
		id: '02',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سماعات', subCateTow: 'شاحن', subCateThree: 'ايفون' },
		productImg: carImage,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '03',
		idNumbers: 996,
		productName: 'لابتوتب',
		subNumber: 6,
		subCategories: { subCateOne: 'HP', subCateTow: 'DELL', subCateThree: 'LENOVO' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '04',
		idNumbers: 186,
		productName: 'جوالات',
		subNumber: 12,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: carImage,
		editIcon: editIcon,
		opened: false,
	},
	{
		id: '05',
		idNumbers: 9586,
		productName: 'لابتوتب',
		subNumber: 6,
		subCategories: { subCateOne: 'HP', subCateTow: 'DELL', subCateThree: 'LENOVO' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '06',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '07',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '08',
		idNumbers: 9586,
		productName: 'لابتوتب',
		subNumber: 6,
		subCategories: { subCateOne: 'HP', subCateTow: 'DELL', subCateThree: 'LENOVO' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '09',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '10',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '11',
		idNumbers: 9586,
		productName: 'لابتوتب',
		subNumber: 6,
		subCategories: { subCateOne: 'HP', subCateTow: 'DELL', subCateThree: 'LENOVO' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '12',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '13',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '14',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '15',
		idNumbers: 9586,
		productName: 'لابتوتب',
		subNumber: 6,
		subCategories: { subCateOne: 'HP', subCateTow: 'DELL', subCateThree: 'LENOVO' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
	{
		id: '16',
		idNumbers: 9586,
		productName: 'اكسسوارات',
		subNumber: 4,
		subCategories: { subCateOne: 'سامسونج', subCateTow: 'سوني', subCateThree: 'ايفون' },
		productImg: shose,
		editIcon: editIcon,
		opened: true,
	},
];

// slices
const CategoriesTablesDataSlice = createSlice({
	name: 'categoriesDataTable',
	initialState: categoriesDataTable,
	reducers: {},
});

export const {} = CategoriesTablesDataSlice.actions;
export default CategoriesTablesDataSlice.reducer;
