import { createSlice } from '@reduxjs/toolkit';

// ICON
import { BsThreeDotsVertical } from 'react-icons/bs';
import { ReactComponent as ReportIcon } from '../../data/Icons/icon-24-report.svg';
import person from '../../data/Icons/person.jpg';


const customerDataTable = [
	{
		id: '01',
		customerID: 'DA88',
		customerImage: person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '02',
		customerID: 'DA88',
		customerImage: person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},

	{
		id: '03',
		customerID: 'DA88',
		customerImage: person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '04',
		customerID: 'DA88',
		customerImage: person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '05',
		customerID: 'DA88',
		customerImage: person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '06',
		customerID: 'DA88',
		customerImage: person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '07',
		customerID: 'DA88',
		customerImage: person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},

  {
    id: '08',
    customerID: 'DA88',
    customerImage: person,
    clientName: 'محمد عبد الرحمن',
    registerDate: '2022/Sep/04',
    email: 'exmpale@gmail.com',
    city: 'الرياض',
    deleteIcon: <BsThreeDotsVertical />,
    reportIcon: <ReportIcon />,
  },
	{
		id: '09',
		 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '10',
 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '11',
		 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '12',
		 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},

	{
		id: '13',
	 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '14',
	 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '15',
	 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '16',
	 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '17',
	 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},

	{
		id: '18',
		 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '19',
	 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
	{
		id: '20',
	 customerID: 'DA88',
    customerImage : person,
		clientName: 'محمد عبد الرحمن',
		registerDate: '2022/Sep/04',
		email: 'exmpale@gmail.com',
		city: 'الرياض',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
	},
];

// slices
const CustomerTableDataSlice = createSlice({
	name: 'customerDataTable',
	initialState: customerDataTable,
	reducers: {},
});

export const {} = CustomerTableDataSlice.actions;
export default CustomerTableDataSlice.reducer;
