import { createSlice } from '@reduxjs/toolkit';

const tableData = [
	{
		id: '01',
		pageTitle: 'من نحن',
		nameOfPublished: 'خالد محمد',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '02',
		pageTitle: ' سياسة الخصوصية',
		nameOfPublished: ' ابراهيم نصر',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '03',
		pageTitle: '  المدونة',
		nameOfPublished: '  سامح الحكيم',
		createDate: '2022/Sep/13',
		status: ' محظور',
		opened: false,
		bgColor: '#e0e0e0',
		color: '#71737d',
	},
	{
		id: '04',
		pageTitle: ' سياسة الخصوصية',
		nameOfPublished: ' ابراهيم نصر',
		createDate: '2022/Sep/13',
		status: ' محظور',
		opened: false,
		bgColor: '#e0e0e0',
		color: '#71737d',
	},
	{
		id: '05',
		pageTitle: 'من نحن',
		nameOfPublished: 'خالد محمد',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '06',
		pageTitle: ' سياسة الخصوصية',
		nameOfPublished: ' ابراهيم نصر',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '07',
		pageTitle: ' سياسة الخصوصية',
		nameOfPublished: ' ابراهيم نصر',
		createDate: '2022/Sep/13',
		status: ' محظور',
		opened: false,
		bgColor: '#e0e0e0',
		color: '#71737d',
	},
	{
		id: '08',
		pageTitle: 'من نحن',
		nameOfPublished: 'خالد محمد',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '09',
		pageTitle: 'من نحن',
		nameOfPublished: 'خالد محمد',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '10',
		pageTitle: ' سياسة الخصوصية',
		nameOfPublished: ' ابراهيم نصر',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '11',
		pageTitle: '  المدونة',
		nameOfPublished: '  سامح الحكيم',
		createDate: '2022/Sep/13',
		status: ' محظور',
		opened: false,
		bgColor: '#e0e0e0',
		color: '#71737d',
	},
	{
		id: '12',
		pageTitle: 'من نحن',
		nameOfPublished: 'خالد محمد',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '13',
		pageTitle: ' سياسة الخصوصية',
		nameOfPublished: ' ابراهيم نصر',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
	{
		id: '14',
		pageTitle: '  المدونة',
		nameOfPublished: '  سامح الحكيم',
		createDate: '2022/Sep/13',
		status: ' محظور',
		opened: false,
		bgColor: '#e0e0e0',
		color: '#71737d',
	},
	{
		id: '15',
		pageTitle: '  المدونة',
		nameOfPublished: '  سامح الحكيم',
		createDate: '2022/Sep/13',
		status: ' محظور',
		opened: false,
		bgColor: '#e0e0e0',
		color: '#71737d',
	},
	{
		id: '16',
		pageTitle: ' سياسة الخصوصية',
		nameOfPublished: ' ابراهيم نصر',
		createDate: '2022/Sep/13',
		status: 'تم النشر',
		opened: true,
		bgColor: '#e0ffea',
		color: '#3ae374',
	},
];

// slices
const PagesTableDataSlice = createSlice({
	name: 'PagesTableDataSlice',
	initialState: tableData,
	reducers: {
		Enable: (state, action) => {
			state.isOpen = true;
		},
		Disable: (state, action) => {
			state.isOpen = false;
		},
	},
});

export const { Enable, Disable } = PagesTableDataSlice.actions;
export default PagesTableDataSlice.reducer;
