import { createSlice } from '@reduxjs/toolkit';


// ICON
import { BsThreeDotsVertical } from 'react-icons/bs';
import { GoCheck } from 'react-icons/go';

import { ReactComponent as ReportIcon } from '../../data/Icons/icon-24-report.svg';
import { ReactComponent as DeadLineIcon } from '../../data/Icons/icon-24-deadline.svg';
import { ReactComponent as HourGleass } from '../../data/Icons/icon-24-hourgleass_half.svg';





const supportDataTable = [
	{
		id: '01',
		clientName: 'محمد عبد الرحمن',
		connectionType: 'شكوي',
		stats: 'منتهيه',
		statusIcon: <GoCheck />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#3ae374',
		color: '#fff',
	},
	{
		id: '02',
		clientName: 'حسن أحمد ',
		connectionType: 'اقتراح',
		stats: 'غير منتهيه',
		statusIcon: <DeadLineIcon />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#d3d3d3',
		color: '#fff',
	},

	{
		id: '03',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '04',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '05',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		statusIcon: <HourGleass />,
		stats: ' قيد المعالجه',
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '06',
		clientName: 'محمد عبد الرحمن',
		connectionType: 'شكوي',
		stats: 'منتهيه',
		statusIcon: <GoCheck />,
		statusIcon: <GoCheck />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#3ae374',
		color: '#fff',
	},
	{
		id: '07',
		clientName: 'حسن أحمد ',
		connectionType: 'اقتراح',
		stats: 'غير منتهيه',
		statusIcon: <DeadLineIcon />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#d3d3d3',
		color: '#0077ff',
	},

	{
		id: '08',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '09',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '10',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '11',
		clientName: 'محمد عبد الرحمن',
		connectionType: 'شكوي',
		stats: 'منتهيه',
		statusIcon: <GoCheck />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#3ae374',
		color: '#fff',
	},
	{
		id: '12',
		clientName: 'حسن أحمد ',
		connectionType: 'اقتراح',
		stats: 'غير منتهيه',
		statusIcon: <DeadLineIcon />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#d3d3d3',
		color: '#0077ff',
	},

	{
		id: '13',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '14',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '15',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '16',
		clientName: 'محمد عبد الرحمن',
		connectionType: 'شكوي',
		stats: 'منتهيه',
		statusIcon: <GoCheck />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#3ae374',
		color: '#fff',
	},
	{
		id: '17',
		clientName: 'حسن أحمد ',
		connectionType: 'اقتراح',
		stats: 'غير منتهيه',
		statusIcon: <DeadLineIcon />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#d3d3d3',
		color: '#fff',
	},

	{
		id: '18',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '19',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
	{
		id: '20',
		clientName: 'عبدالرحمن محمد ',
		connectionType: 'استفسار',
		stats: ' قيد المعالجه',
		statusIcon: <HourGleass />,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		bgColor: '#ff9f1a',
		color: '#fff',
	},
];

// slices
const supportTablesDataSlice = createSlice({
	name: 'supportDataTable',
	initialState: supportDataTable,
	reducers: {},
});

export const {} = supportTablesDataSlice.actions;
export default supportTablesDataSlice.reducer;
