import { createSlice } from '@reduxjs/toolkit';

// ICON
import { BsThreeDotsVertical } from 'react-icons/bs';
import { ReactComponent as ReportIcon } from '../../data/Icons/icon-24-report.svg';
import { ReactComponent as EditIcon } from '../../data/Icons/icon-24-edit.svg';


const usersDataTable = [
	{
		id: '01',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '02',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},

	{
		id: '03',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '04',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '05',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '06',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '07',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},

	{
		id: '08',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '09',
	userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '10',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '11',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '12',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},

	{
		id: '13',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '14',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '15',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '16',
		customerID: 'DA88',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '17',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},

	{
		id: '18',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '19',
		userName: 'صلاح راغب الأحمد ',
		email: 'exmpale@gmail.com',
		level: 'سوبر ادمن',
		status: false,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
	{
		id: '20',
		userName: 'محمد عبد الرحمن',
		email: 'exmpale@gmail.com',
		level: 'ادمن',
		status: true,
		deleteIcon: <BsThreeDotsVertical />,
		reportIcon: <ReportIcon />,
		edit: <EditIcon />,
	},
];

// slices
const ManagementTableDataSlice = createSlice({
	name: 'customerDataTable',
	initialState: usersDataTable,
	reducers: {},
});

export const {} = ManagementTableDataSlice.actions;
export default ManagementTableDataSlice.reducer;
