export { default as SalesReports } from './SalesReports';
export { default as CustomersReports } from './CustomersReports';

export { default as AddCategory } from './AddCategory';
export { default as AddProduct } from './AddProduct';
export { default as AddCoupon } from './AddCoupon';
export { default as EditCoupon } from './EditCoupon';
export { default as AddCustomer } from './AddCustomer';
export { default as AddNewUser } from './AddNewUser';
export { default as EditUserPage } from './EditUserPage';
export { default as CreateOffer } from './CreateOffer';
export { default as CreatePage } from './CreatePage';
export { default as OrderDetails } from './OrderDetails';
export { default as CourseDetails } from './CourseDetails';
export { default as SupportDetails } from './SupportDetails';
export { default as CustomerData } from './CustomerData';
export { default as ClientData } from './ClientData';
export { default as JobTitles } from './JobTitles';
export { default as Comments } from './Comments';
// export { default as SalesReport } from './SalesReport';
// export { default as SalesReport } from './SalesReport';
// export { default as SalesReport } from './SalesReport';
// export { default as SalesReport } from './SalesReport';
// export { default as SalesReport } from './SalesReport';
